from tkinter import *
win=Tk()
win.geometry("200x200")
top=Frame(win)
bot=Frame(win)
top.pack()#side=LEFT
bot.pack(side=BOTTOM)
#win.geometry("200X200")
#bot2.pack(side="top")
mylable=Label(text="This ",fg="red",bg="green")
Button1=Button(top,text="Button1",fg="yellow",bg="red")
Button2=Button(bot,text="Button1",fg="green",bg="yellow")
Button3=Button(top,text="Button1",fg="yellow",bg="red")
Button4=Button(bot,text="Button1",fg="green",bg="red")
Button5=Button(top,text="Button1",fg="yellow",bg="red")
Button6=Button(bot,text="Button1",fg="green",bg="red")
mylable.pack(side=LEFT,fill=Y)
Button1.pack(side=LEFT)
Button2.pack(side=BOTTOM)
Button3.pack(side=LEFT)
Button4.pack(side=BOTTOM)
Button5.pack(side=BOTTOM)
Button6.pack(side=LEFT)
win.mainloop()